fix assert_ovn_containers_running for podified envs
This function verified whether the ovn_metadata_agent and ovn_controller
containers are running on dataplane nodes from podified environments.

It didn't expect container names exactly match and due to that the test
fails with certain configuration: when BGP is configured with
ovn-routing, an extra container named "bgp_ovn_controller" is added,
making the test test_ovn_containers_running fail due to:
AssertionError: container states mismatched:
only one running container ovn_controller was expected on node compute-zi9z0dgn-0, but got 2! :

Change-Id: I41e03bf29462db617f6c2ee2528d58b37396e2e7